### PR TITLE
fix(batcher): include checksum in zlib-compressed channel encoding

### PR DESCRIPTION
**Pull request by 0xbenyun**
## Description

This PR addresses an issue in the batcher where the checksum was not being included during the compression of rlp_spanbatches using zlib. The checksum is now correctly included in the compressed data.

This work originated from an investigation into a derivation failure observed in Kona, during which it was discovered that the checksum was missing in the compressed output.

Additionally, a related upstream PR [#10002](https://github.com/ethereum-optimism/optimism/pull/10002), primarily focused on optimization and refactoring, also resolved this checksum issue as part of its broader changes.

### CODE REVIEW

**Comment by kangsorang** [comment]
I think the batch derivation process involves a read through zlib.Reader and that includes checksum verification.
I'm curious to know how BatchReader's behavior has passed this checksum issue so far.

**Review by sm-stack — APPROVED** [review]
LGTM

**Review by Pangssu — APPROVED** [review]

**Comment by 0xbenyun** [comment]
> I think the batch derivation process involves a read through zlib.Reader and that includes checksum verification. I'm curious to know how BatchReader's behavior has passed this checksum issue so far.

I have confirmed that the zlib.Reader in Go does not always verify the checksum in all cases. Therefore, in BatchReader, it performs decompression without checking the checksum, regardless of its presence.

**Review by kangsorang — APPROVED** [review]
LGTM

**Review by Pangssu — APPROVED** [review]

**Review by seolaoh — APPROVED** [review]

**Pull request merged**
