### PR TITLE
chore(contracts): upgrade semver to v1.0.0

### PR DESCRIPTION
**Pull request by 0xHansLee**
# Description

Upgraded the semver of contracts to `v1.0.0`

### CODE REVIEW

**Review by kangsorang — APPROVED** [review]
LGTM

**Review by seolaoh — APPROVED** [review]
LGTM

**Comment by seolaoh** [comment]
Regardless of this PR, wouldn't it be necessary to bump the version of all `package.json` files to `1.0.0`?

**Review by Pangssu — APPROVED** [review]

**Comment by 0xHansLee** [comment]
> Regardless of this PR, wouldn't it be necessary to bump the version of all package.json files to 1.0.0?

Good. I'll publish a new version of each packages.

**Pull request merged**
