### PR TITLE
feat(contracts): improvement for the next validator selection

### PR DESCRIPTION
**Pull request by kangsorang**
# Description

Related to https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/18 reported by theori audit.
Add more hash elements for next validator selection.

### CODE REVIEW

**Review by 0xHansLee — APPROVED** [review]
LGTM

**Review by Pangssu — APPROVED** [review]
LGTM

**Review by seolaoh — APPROVED** [review]
LGTM, but please change `impovement` to `improvement` in commit message, and rebase onto `dev` and update bindings and gas snapshot.

**Comment by seolaoh** [comment]
Could you please check the test success after rebasing, then merge it next time? Thank you.

**Comment by 0xHansLee** [comment]
> Could you please check the test success after rebasing, then merge it next time? Thank you.

I agree

**Pull request merged**
