### PR TITLE
docs: add security audit by ChainLight

### PR DESCRIPTION
**Pull request by 0xHansLee**

### CODE REVIEW

**Comment by seolaoh** [comment]
How about add a line in `README.md` like below?
`See [here](./audits) for security audit reports.`

**Comment by 0xHansLee** [comment]
> How about add a line in README.md like below?
See [here](./audits) for security audit reports.

I also thought about it, but I didn't. I thought we don't need to state here about audits because it is `About Kroma`. 
It'd better to make a separate section for security audits. wdyt?

**Comment by seolaoh** [comment]
> > How about add a line in README.md like below?
> > See [here](./audits) for security audit reports.
> 
> I also thought about it, but I didn't. I thought we don't need to state here about audits because it is `About Kroma`. It'd better to make a separate section for security audits. wdyt?

Yes, I suggested it to add the instruction about audit report somewhere in this repository. It does not need to be in `README.md`.

**Review by Pangssu — APPROVED** [review]

**Review by kangsorang — APPROVED** [review]
LGTM

**Review by seolaoh — APPROVED** [review]
LGTM

**Pull request merged**
