### PR TITLE
chore: re-deploy sepolia contracts using fixed deploy script

### PR DESCRIPTION
**Pull request by Pangssu**
# Description

There was an issue with the deployment script not calling upgradeAndCall.
Fixed this issue and re-deployed contracts.

Related: #105

### CODE REVIEW

**Comment by seolaoh** [comment]
Don't we need to update [components/node/chaincfg/chains.go](https://github.com/kroma-network/kroma/pull/105/files#diff-d41298b73c453f7a6cb18f91d7113f7229585d71de4ccf191e9b84e10a691f09)? The L1 genesis block ID and `BatchInboxAddress`?

**Comment by seolaoh** [comment]
Could you apply [this comment](https://github.com/kroma-network/kroma/pull/105/files#r1254368529)?

**Review by 0xHansLee — APPROVED** [review]
Lgtm

**Review by seolaoh — APPROVED** [review]
LGTM

**Pull request merged**
