### PR TITLE
chore: add config file for semantic-prs

### PR DESCRIPTION
**Pull request by seolaoh**

### CODE REVIEW

**Review by Pangssu — APPROVED** [review]

**Review by 0xHansLee — COMMENTED** [review]
`targetUrl` is also useful for us. wdyt?

**Comment by seolaoh** [comment]
> `targetUrl` is also useful for us. wdyt?

I did not understand what it is for. Could you explain it? 🙏

**Comment by 0xHansLee** [comment]
> I did not understand what it is for. Could you explain it? 🙏

Link to our `.gitmessage` to provide guide for our git PR convention. 
However, it's not very readable, so you can add it later as a more readable document.

**Review by 0xHansLee — APPROVED** [review]
Thanks!

**Review by kangsorang — APPROVED** [review]
lgtm

**Pull request merged**
