### PR TITLE
chore(contract): initialization for ReentrancyGuardUpgradeable

### PR DESCRIPTION
**Pull request by kangsorang**
# Description

Related [[KROMA-014] Missing initialization for ReentrancyGuardUpgradeable in MultiSigWallet and ValidatorPool contract](https://github.com/chainlight-io/2023-kroma-network-audit-issues-client/issues/14) reported by theori audit.

The ReentrancyGuardUpgradeable contract of the current version works even if not initialized. 
However, it can become problematic with a change in the initialization function or other logic due to a library upgrade.

### CODE REVIEW

**Review by Pangssu — APPROVED** [review]
LGTM

**Comment by seolaoh** [comment]
The commit message should not exceed max 80 characters in a line!

**Review by seolaoh — APPROVED** [review]
LGTM

**Review by 0xHansLee — APPROVED** [review]
lgtm

**Pull request merged**
