### PR TITLE
feat(contracts): unify token burn permissions with mint

### PR DESCRIPTION
**Pull request by kangsorang**
# Description

Unify the permission to burn tokens with the permission to mint. 

Tokens will managed consistently through governance.

### CODE REVIEW

**Comment by Pangssu** [comment]
Why don't you remain the standard `burn()`, and add `safeBurn()`?

**Comment by kangsorang** [comment]
> Why don't you remain the standard `burn()`, and add `safeBurn()`?

The idea was to not allow token holders to self-burn, but to manage tokens solely through governance.

**Review by seolaoh — APPROVED** [review]
LGTM

**Comment by seolaoh** [comment]
Please limit the commit msg in 80 characters.

**Review by 0xHansLee — APPROVED** [review]
lgtm

**Review by Pangssu — APPROVED** [review]

**Pull request merged**
