### PR TITLE
chore: remove all configurations for internal testnet

### PR DESCRIPTION
**Pull request by Pangssu**
# Description

Remove all deployments for networks that you use internally, such as the `easel` network, as they are managed in private repositories.

### CODE REVIEW

**Review by 0xHansLee — COMMENTED** [review]
Could you delete the testdata (`bindings/hardhat/testdata/deployments/easel/*.json`)?

**Comment by chokobole** [comment]
Why the `go.sum` is updated?

**Comment by seolaoh** [comment]
> Could you delete the testdata (`bindings/hardhat/testdata/deployments/easel/*.json`)?

LGTM except for this comment.

**Review by chokobole — APPROVED** [review]
LGTM

**Review by seolaoh — APPROVED** [review]
LGTM

**Review by 0xHansLee — APPROVED** [review]
Good. Let's merge after all checks passed.

**Pull request merged**
