### PR TITLE
chore: revise issue template

### PR DESCRIPTION
**Pull request by seolaoh**
# Description

Added expected behavior.

### CODE REVIEW

**Comment by kangsorang** [comment]
If the issue type is not a bug, the required fields below seem a bit awkward. Is there a better way to do this?

**Comment by seolaoh** [comment]
> If the issue type is not a bug, the required fields below seem a bit awkward. Is there a better way to do this?

Then it would be better to separate the issue template to bug report and feature request like this [reference](https://github.com/ethereum-optimism/optimism/issues/new/choose). But I think it's just ok to use this template for general purpose.

**Comment by seolaoh** [comment]
I will update [the issue template of .github repository](https://github.com/kroma-network/.github/blob/main/.github/ISSUE_TEMPLATE/issue_template.yaml) also, when this PR merged.

**Review by kangsorang — APPROVED** [review]
lgtm

**Comment by seolaoh** [comment]
@kangsorang I made the issue template more general. Please review again :)

**Review by chokobole — APPROVED** [review]
LGTM

**Review by 0xHansLee — APPROVED** [review]
lgtm

**Pull request merged**
