### PR TITLE
feat: apply audit results about token minting and distribution

### PR DESCRIPTION
**Pull request by seolaoh**
# Description

Since we use `Ownable2Step` contract to set the owner of `GovernanceToken` and `MintManager`, the new owner should accept the ownership. The purpose is to reduce human error, so I thought it is more appropriate to follow this step when deploying the contracts via deploy script. So the deploy step is changed like below.

### Deploy Process

1. deploy `L1GovernanceTokenProxy` contract
2. deploy `L1MintManager` contract
  - `mintManagerOwner` is set as `pendingOwner` of `L1MintManager`
3. deploy `L1GovernanceToken` contract, upgrade proxy, and initialize
  - `L1MintManager` is set as `pendingOwner` of `L1GovernanceToken`
  - `mintManagerOwner` is set as admin of `L1GovernanceTokenProxy`
4. call `L1MintManager.acceptOwnership()`, `L1MintManager.acceptOwnershipOfToken()` by `mintManagerOwner` > confirm ownership transfer of `L1MintManager`, `L1GovernanceToken`
5. change admin of `L1GovernanceTokenProxy` to zero address by `mintManagerOwner`

### Test Transactions on Holesky
- [`acceptOwnership` of `L1MintManager`](https://holesky.etherscan.io/tx/0x3c273259889a5c95b0bd662d6649bf82ade451a928db7ab1485095a9d3d3332b)
- [`acceptOwnership` of `L1GovernanceToken`](https://holesky.etherscan.io/tx/0xeedd4ffacbefcc6dd45b753eb81ff445cd377e22a62bb02c85ff7efb5e570f73)

### CODE REVIEW

**Review by 0xHansLee — APPROVED** [review]
LGTM

**Comment by 0xHansLee** [comment]
Could you update the scenario for deployments you wrote in confluence?

**Comment by seolaoh** [comment]
> Could you update the scenario for deployments you wrote in confluence?

I already updated it.

**Comment by 0xHansLee** [comment]
Should this PR be merged to `dev` directly?

**Comment by seolaoh** [comment]
> Should this PR be merged to `dev` directly?

No, it should be merged after #335. Or it can be merged before #335 with moving the commit related to governance token from this PR to that PR.

**Review by Pangssu — APPROVED** [review]

**Review by kangsorang — APPROVED** [review]

**Pull request merged**
